version: '3.8'

services:
  bot:
    build: .
    container_name: ayi-bot
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    networks:
      - ayi-network

  mongodb:
    image: mongo:7-jammy
    container_name: ayi-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - mongodb_data:/data/db
    networks:
      - ayi-network

volumes:
  mongodb_data:

networks:
  ayi-network:
    driver: bridge